import type { DiffData } from "@/types/diff";

/**
 * Mock diff data keyed by branch ID.
 * Each entry contains realistic file diffs matching the round-2-polish stack.
 */
export const mockDiffDataByBranch: Record<string, DiffData> = {
  // Branch b-001: 1-initial — scaffold with dark design system
  "b-001": {
    total_additions: 48,
    total_deletions: 12,
    files: [
      {
        path: "app/frontend/package.json",
        change_type: "added",
        additions: 28,
        deletions: 0,
        hunks: [
          {
            header: "@@ -0,0 +1,28 @@",
            lines: [
              { type: "add", old_num: null, new_num: 1, content: "{" },
              { type: "add", old_num: null, new_num: 2, content: '  "name": "@stack-bench/frontend",' },
              { type: "add", old_num: null, new_num: 3, content: '  "private": true,' },
              { type: "add", old_num: null, new_num: 4, content: '  "version": "0.0.1",' },
              { type: "add", old_num: null, new_num: 5, content: '  "type": "module",' },
              { type: "add", old_num: null, new_num: 6, content: '  "scripts": {' },
              { type: "add", old_num: null, new_num: 7, content: '    "dev": "vite",' },
              { type: "add", old_num: null, new_num: 8, content: '    "build": "tsc -b && vite build",' },
              { type: "add", old_num: null, new_num: 9, content: '    "preview": "vite preview",' },
              { type: "add", old_num: null, new_num: 10, content: '    "typecheck": "tsc --noEmit"' },
              { type: "add", old_num: null, new_num: 11, content: "  }," },
              { type: "add", old_num: null, new_num: 12, content: '  "dependencies": {' },
              { type: "add", old_num: null, new_num: 13, content: '    "react": "^18.3.0",' },
              { type: "add", old_num: null, new_num: 14, content: '    "react-dom": "^18.3.0"' },
              { type: "add", old_num: null, new_num: 15, content: "  }" },
              { type: "add", old_num: null, new_num: 16, content: "}" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/index.css",
        change_type: "added",
        additions: 20,
        deletions: 0,
        hunks: [
          {
            header: "@@ -0,0 +1,20 @@",
            lines: [
              { type: "add", old_num: null, new_num: 1, content: '@import "tailwindcss";' },
              { type: "add", old_num: null, new_num: 2, content: "" },
              { type: "add", old_num: null, new_num: 3, content: "/*" },
              { type: "add", old_num: null, new_num: 4, content: " * Stack Bench — Dark Design System Tokens" },
              { type: "add", old_num: null, new_num: 5, content: " */" },
              { type: "add", old_num: null, new_num: 6, content: ":root {" },
              { type: "add", old_num: null, new_num: 7, content: "  --bg-canvas: #0d1117;" },
              { type: "add", old_num: null, new_num: 8, content: "  --bg-surface: #161b22;" },
              { type: "add", old_num: null, new_num: 9, content: "  --bg-surface-hover: #1c2128;" },
              { type: "add", old_num: null, new_num: 10, content: "  --border: #30363d;" },
              { type: "add", old_num: null, new_num: 11, content: "  --border-muted: #21262d;" },
              { type: "add", old_num: null, new_num: 12, content: "  --fg-default: #e6edf3;" },
              { type: "add", old_num: null, new_num: 13, content: "  --fg-muted: #7d8590;" },
              { type: "add", old_num: null, new_num: 14, content: "  --fg-subtle: #484f58;" },
              { type: "add", old_num: null, new_num: 15, content: "  --accent: #58a6ff;" },
              { type: "add", old_num: null, new_num: 16, content: "  --green: #3fb950;" },
              { type: "add", old_num: null, new_num: 17, content: "  --red: #f85149;" },
              { type: "add", old_num: null, new_num: 18, content: "}" },
            ],
          },
        ],
      },
    ],
  },

  // Branch b-002: 2-design-polish — viewed toggle, emerald palette, fonts
  "b-002": {
    total_additions: 142,
    total_deletions: 18,
    files: [
      {
        path: "app/frontend/src/components/atoms/ViewedToggle/ViewedToggle.tsx",
        change_type: "added",
        additions: 38,
        deletions: 0,
        hunks: [
          {
            header: "@@ -0,0 +1,38 @@",
            lines: [
              { type: "add", old_num: null, new_num: 1, content: 'import { cn } from "@/lib/utils";' },
              { type: "add", old_num: null, new_num: 2, content: "" },
              { type: "add", old_num: null, new_num: 3, content: "interface ViewedToggleProps {" },
              { type: "add", old_num: null, new_num: 4, content: "  viewed: boolean;" },
              { type: "add", old_num: null, new_num: 5, content: "  onChange: (viewed: boolean) => void;" },
              { type: "add", old_num: null, new_num: 6, content: "}" },
              { type: "add", old_num: null, new_num: 7, content: "" },
              { type: "add", old_num: null, new_num: 8, content: "function ViewedToggle({ viewed, onChange }: ViewedToggleProps) {" },
              { type: "add", old_num: null, new_num: 9, content: "  return (" },
              { type: "add", old_num: null, new_num: 10, content: "    <button" },
              { type: "add", old_num: null, new_num: 11, content: '      type="button"' },
              { type: "add", old_num: null, new_num: 12, content: "      onClick={() => onChange(!viewed)}" },
              { type: "add", old_num: null, new_num: 13, content: "      className={cn(" },
              { type: "add", old_num: null, new_num: 14, content: '        "text-[10px] px-1.5 py-0.5 rounded-full transition-colors",' },
              { type: "add", old_num: null, new_num: 15, content: "        viewed" },
              { type: "add", old_num: null, new_num: 16, content: '          ? "bg-[var(--accent-emerald-dim)] text-[var(--accent-emerald)]"' },
              { type: "add", old_num: null, new_num: 17, content: '          : "text-[var(--fg-subtle)] hover:text-[var(--fg-muted)]"' },
              { type: "add", old_num: null, new_num: 18, content: "      )}" },
              { type: "add", old_num: null, new_num: 19, content: "    >" },
              { type: "add", old_num: null, new_num: 20, content: '      {viewed ? "Viewed" : "View"}' },
              { type: "add", old_num: null, new_num: 21, content: "    </button>" },
              { type: "add", old_num: null, new_num: 22, content: "  );" },
              { type: "add", old_num: null, new_num: 23, content: "}" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/index.css",
        change_type: "modified",
        additions: 12,
        deletions: 2,
        hunks: [
          {
            header: "@@ -28,8 +28,20 @@",
            lines: [
              { type: "context", old_num: 28, new_num: 28, content: "  --accent: #58a6ff;" },
              { type: "context", old_num: 29, new_num: 29, content: "  --green: #3fb950;" },
              { type: "context", old_num: 30, new_num: 30, content: "  --red: #f85149;" },
              { type: "del", old_num: 31, new_num: null, content: "  --purple: #a371f7;" },
              { type: "del", old_num: 32, new_num: null, content: "}" },
              { type: "add", old_num: null, new_num: 31, content: "  --purple: #bc8cff;" },
              { type: "add", old_num: null, new_num: 32, content: "  --yellow: #d29922;" },
              { type: "add", old_num: null, new_num: 33, content: "" },
              { type: "add", old_num: null, new_num: 34, content: "  /* Emerald Accents */" },
              { type: "add", old_num: null, new_num: 35, content: "  --accent-emerald: #6ee7b7;" },
              { type: "add", old_num: null, new_num: 36, content: "  --accent-emerald-dim: #065f46;" },
              { type: "add", old_num: null, new_num: 37, content: "" },
              { type: "add", old_num: null, new_num: 38, content: "  /* Semantic Backgrounds */" },
              { type: "add", old_num: null, new_num: 39, content: "  --green-bg: #12261e;" },
              { type: "add", old_num: null, new_num: 40, content: "  --red-bg: #28171a;" },
              { type: "add", old_num: null, new_num: 41, content: "}" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/components/molecules/DiffFileHeader/DiffFileHeader.tsx",
        change_type: "modified",
        additions: 8,
        deletions: 2,
        hunks: [
          {
            header: "@@ -55,8 +55,16 @@",
            lines: [
              { type: "context", old_num: 55, new_num: 55, content: "      <span className=\"shrink-0\">" },
              { type: "context", old_num: 56, new_num: 56, content: "        <DiffStat additions={file.additions} deletions={file.deletions} />" },
              { type: "context", old_num: 57, new_num: 57, content: "      </span>" },
              { type: "del", old_num: 58, new_num: null, content: "    </div>" },
              { type: "del", old_num: 59, new_num: null, content: "  );" },
              { type: "add", old_num: null, new_num: 58, content: "" },
              { type: "add", old_num: null, new_num: 59, content: "      {onViewedChange && (" },
              { type: "add", old_num: null, new_num: 60, content: "        <span className=\"shrink-0 ml-2\">" },
              { type: "add", old_num: null, new_num: 61, content: "          <ViewedToggle viewed={viewed} onChange={onViewedChange} />" },
              { type: "add", old_num: null, new_num: 62, content: "        </span>" },
              { type: "add", old_num: null, new_num: 63, content: "      )}" },
              { type: "add", old_num: null, new_num: 64, content: "    </div>" },
              { type: "add", old_num: null, new_num: 65, content: "  );" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/components/molecules/ActionBar/ActionBar.tsx",
        change_type: "modified",
        additions: 84,
        deletions: 14,
        hunks: [
          {
            header: "@@ -1,18 +1,88 @@",
            lines: [
              { type: "del", old_num: 1, new_num: null, content: "function ActionBar() {" },
              { type: "del", old_num: 2, new_num: null, content: "  return (" },
              { type: "del", old_num: 3, new_num: null, content: "    <div className=\"flex items-center gap-2 px-4 py-2\">" },
              { type: "del", old_num: 4, new_num: null, content: "      <span>Action Bar</span>" },
              { type: "del", old_num: 5, new_num: null, content: "    </div>" },
              { type: "del", old_num: 6, new_num: null, content: "  );" },
              { type: "del", old_num: 7, new_num: null, content: "}" },
              { type: "add", old_num: null, new_num: 1, content: 'import { Icon } from "@/components/atoms/Icon";' },
              { type: "add", old_num: null, new_num: 2, content: 'import { Button } from "@/components/atoms/Button";' },
              { type: "add", old_num: null, new_num: 3, content: "" },
              { type: "add", old_num: null, new_num: 4, content: "interface ActionBarProps {" },
              { type: "add", old_num: null, new_num: 5, content: "  fileCount?: number;" },
              { type: "add", old_num: null, new_num: 6, content: "  additions?: number;" },
              { type: "add", old_num: null, new_num: 7, content: "  deletions?: number;" },
              { type: "add", old_num: null, new_num: 8, content: "  onCollapseAll?: () => void;" },
              { type: "add", old_num: null, new_num: 9, content: "  onExpandAll?: () => void;" },
              { type: "add", old_num: null, new_num: 10, content: "}" },
            ],
          },
        ],
      },
    ],
  },

  // Branch b-003: 3-line-interactions — line selection, hover actions
  "b-003": {
    total_additions: 89,
    total_deletions: 34,
    files: [
      {
        path: "app/frontend/src/components/atoms/DiffLine/DiffLine.tsx",
        change_type: "modified",
        additions: 45,
        deletions: 12,
        hunks: [
          {
            header: "@@ -1,15 +1,48 @@",
            lines: [
              { type: "context", old_num: 1, new_num: 1, content: 'import { cn } from "@/lib/utils";' },
              { type: "context", old_num: 2, new_num: 2, content: 'import type { DiffLine as DiffLineType } from "@/types/diff";' },
              { type: "context", old_num: 3, new_num: 3, content: "" },
              { type: "del", old_num: 4, new_num: null, content: "interface DiffLineProps {" },
              { type: "del", old_num: 5, new_num: null, content: "  line: DiffLineType;" },
              { type: "del", old_num: 6, new_num: null, content: "}" },
              { type: "add", old_num: null, new_num: 4, content: "interface DiffLineProps {" },
              { type: "add", old_num: null, new_num: 5, content: "  line: DiffLineType;" },
              { type: "add", old_num: null, new_num: 6, content: "  selected?: boolean;" },
              { type: "add", old_num: null, new_num: 7, content: "  onSelect?: (lineNum: number, shiftKey: boolean) => void;" },
              { type: "add", old_num: null, new_num: 8, content: "  onHoverAction?: (lineNum: number) => void;" },
              { type: "add", old_num: null, new_num: 9, content: "}" },
              { type: "context", old_num: 7, new_num: 10, content: "" },
              { type: "del", old_num: 8, new_num: null, content: "function DiffLine({ line }: DiffLineProps) {" },
              { type: "add", old_num: null, new_num: 11, content: "function DiffLine({ line, selected, onSelect, onHoverAction }: DiffLineProps) {" },
              { type: "add", old_num: null, new_num: 12, content: "  const lineNum = line.new_num ?? line.old_num;" },
              { type: "add", old_num: null, new_num: 13, content: "" },
              { type: "add", old_num: null, new_num: 14, content: "  const handleClick = (e: React.MouseEvent) => {" },
              { type: "add", old_num: null, new_num: 15, content: "    if (lineNum != null && onSelect) {" },
              { type: "add", old_num: null, new_num: 16, content: "      onSelect(lineNum, e.shiftKey);" },
              { type: "add", old_num: null, new_num: 17, content: "    }" },
              { type: "add", old_num: null, new_num: 18, content: "  };" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/components/molecules/DiffHunk/DiffHunk.tsx",
        change_type: "modified",
        additions: 22,
        deletions: 8,
        hunks: [
          {
            header: "@@ -1,12 +1,26 @@",
            lines: [
              { type: "context", old_num: 1, new_num: 1, content: 'import { DiffLine } from "@/components/atoms/DiffLine";' },
              { type: "context", old_num: 2, new_num: 2, content: 'import type { DiffHunk as DiffHunkType } from "@/types/diff";' },
              { type: "context", old_num: 3, new_num: 3, content: "" },
              { type: "del", old_num: 4, new_num: null, content: "interface DiffHunkProps {" },
              { type: "del", old_num: 5, new_num: null, content: "  hunk: DiffHunkType;" },
              { type: "del", old_num: 6, new_num: null, content: "}" },
              { type: "add", old_num: null, new_num: 4, content: "interface DiffHunkProps {" },
              { type: "add", old_num: null, new_num: 5, content: "  hunk: DiffHunkType;" },
              { type: "add", old_num: null, new_num: 6, content: "  selectedLines?: Set<number>;" },
              { type: "add", old_num: null, new_num: 7, content: "  onSelectLine?: (lineNum: number, shiftKey: boolean) => void;" },
              { type: "add", old_num: null, new_num: 8, content: "}" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/components/organisms/FilesChangedPanel/FilesChangedPanel.tsx",
        change_type: "modified",
        additions: 22,
        deletions: 14,
        hunks: [
          {
            header: "@@ -1,18 +1,26 @@",
            lines: [
              { type: "context", old_num: 1, new_num: 1, content: 'import { useState } from "react";' },
              { type: "del", old_num: 2, new_num: null, content: 'import { DiffFile } from "@/components/molecules/DiffFile";' },
              { type: "add", old_num: null, new_num: 2, content: 'import { useState, useCallback } from "react";' },
              { type: "add", old_num: null, new_num: 3, content: 'import { DiffFile } from "@/components/molecules/DiffFile";' },
              { type: "context", old_num: 3, new_num: 4, content: 'import type { DiffData } from "@/types/diff";' },
              { type: "context", old_num: 4, new_num: 5, content: "" },
              { type: "del", old_num: 5, new_num: null, content: "interface FilesChangedPanelProps {" },
              { type: "del", old_num: 6, new_num: null, content: "  diffData: DiffData;" },
              { type: "del", old_num: 7, new_num: null, content: "}" },
              { type: "add", old_num: null, new_num: 6, content: "interface FilesChangedPanelProps {" },
              { type: "add", old_num: null, new_num: 7, content: "  diffData: DiffData;" },
              { type: "add", old_num: null, new_num: 8, content: "  forceExpanded?: boolean | null;" },
              { type: "add", old_num: null, new_num: 9, content: "}" },
            ],
          },
        ],
      },
    ],
  },

  // Branch b-004: 4-agent-panel — collapsible agent panel
  "b-004": {
    total_additions: 67,
    total_deletions: 4,
    files: [
      {
        path: "app/frontend/src/components/organisms/AgentPanel/AgentPanel.tsx",
        change_type: "added",
        additions: 52,
        deletions: 0,
        hunks: [
          {
            header: "@@ -0,0 +1,52 @@",
            lines: [
              { type: "add", old_num: null, new_num: 1, content: 'import { cn } from "@/lib/utils";' },
              { type: "add", old_num: null, new_num: 2, content: 'import { Icon } from "@/components/atoms/Icon";' },
              { type: "add", old_num: null, new_num: 3, content: "" },
              { type: "add", old_num: null, new_num: 4, content: "interface AgentPanelProps {" },
              { type: "add", old_num: null, new_num: 5, content: "  open: boolean;" },
              { type: "add", old_num: null, new_num: 6, content: "  onClose: () => void;" },
              { type: "add", old_num: null, new_num: 7, content: "}" },
              { type: "add", old_num: null, new_num: 8, content: "" },
              { type: "add", old_num: null, new_num: 9, content: "function AgentPanel({ open, onClose }: AgentPanelProps) {" },
              { type: "add", old_num: null, new_num: 10, content: "  if (!open) return null;" },
              { type: "add", old_num: null, new_num: 11, content: "" },
              { type: "add", old_num: null, new_num: 12, content: "  return (" },
              { type: "add", old_num: null, new_num: 13, content: "    <aside className={cn(" },
              { type: "add", old_num: null, new_num: 14, content: '      "w-80 border-l border-[var(--border)] bg-[var(--bg-surface)]",' },
              { type: "add", old_num: null, new_num: 15, content: '      "flex flex-col h-full"' },
              { type: "add", old_num: null, new_num: 16, content: "    )}>" },
              { type: "add", old_num: null, new_num: 17, content: '      <div className="flex items-center justify-between px-4 py-3 border-b border-[var(--border)]">' },
              { type: "add", old_num: null, new_num: 18, content: '        <span className="text-sm font-medium text-[var(--fg-default)]">Agent</span>' },
              { type: "add", old_num: null, new_num: 19, content: "        <button onClick={onClose}>" },
              { type: "add", old_num: null, new_num: 20, content: '          <Icon name="x" size="sm" className="text-[var(--fg-muted)]" />' },
              { type: "add", old_num: null, new_num: 21, content: "        </button>" },
              { type: "add", old_num: null, new_num: 22, content: "      </div>" },
              { type: "add", old_num: null, new_num: 23, content: "    </aside>" },
              { type: "add", old_num: null, new_num: 24, content: "  );" },
              { type: "add", old_num: null, new_num: 25, content: "}" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/components/organisms/AgentPanel/index.ts",
        change_type: "added",
        additions: 1,
        deletions: 0,
        hunks: [
          {
            header: "@@ -0,0 +1 @@",
            lines: [
              { type: "add", old_num: null, new_num: 1, content: 'export { AgentPanel } from "./AgentPanel";' },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/App.tsx",
        change_type: "modified",
        additions: 14,
        deletions: 4,
        hunks: [
          {
            header: "@@ -8,6 +8,10 @@",
            lines: [
              { type: "context", old_num: 8, new_num: 8, content: 'import { useFileContent } from "@/hooks/useFileContent";' },
              { type: "context", old_num: 9, new_num: 9, content: "" },
              { type: "context", old_num: 10, new_num: 10, content: "export function App() {" },
              { type: "add", old_num: null, new_num: 11, content: "  const [agentOpen, setAgentOpen] = useState(false);" },
              { type: "add", old_num: null, new_num: 12, content: "" },
              { type: "context", old_num: 11, new_num: 13, content: "  const { data, loading, error } = useStackDetail();" },
            ],
          },
        ],
      },
    ],
  },

  // Branch b-005: 5-sidebar-merge — unified sidebar with diffs/files toggle
  "b-005": {
    total_additions: 112,
    total_deletions: 45,
    files: [
      {
        path: "app/frontend/src/components/atoms/SidebarModeToggle/SidebarModeToggle.tsx",
        change_type: "added",
        additions: 32,
        deletions: 0,
        hunks: [
          {
            header: "@@ -0,0 +1,32 @@",
            lines: [
              { type: "add", old_num: null, new_num: 1, content: 'import { cn } from "@/lib/utils";' },
              { type: "add", old_num: null, new_num: 2, content: 'import type { SidebarMode } from "@/types/sidebar";' },
              { type: "add", old_num: null, new_num: 3, content: "" },
              { type: "add", old_num: null, new_num: 4, content: "interface SidebarModeToggleProps {" },
              { type: "add", old_num: null, new_num: 5, content: "  mode: SidebarMode;" },
              { type: "add", old_num: null, new_num: 6, content: "  onChange: (mode: SidebarMode) => void;" },
              { type: "add", old_num: null, new_num: 7, content: "}" },
              { type: "add", old_num: null, new_num: 8, content: "" },
              { type: "add", old_num: null, new_num: 9, content: 'function SidebarModeToggle({ mode, onChange }: SidebarModeToggleProps) {' },
              { type: "add", old_num: null, new_num: 10, content: "  return (" },
              { type: "add", old_num: null, new_num: 11, content: '    <div className="flex rounded-md border border-[var(--border-muted)]">' },
              { type: "add", old_num: null, new_num: 12, content: "      <button" },
              { type: "add", old_num: null, new_num: 13, content: '        onClick={() => onChange("diffs")}' },
              { type: "add", old_num: null, new_num: 14, content: "        className={cn(" },
              { type: "add", old_num: null, new_num: 15, content: '          "px-2 py-1 text-xs",' },
              { type: "add", old_num: null, new_num: 16, content: '          mode === "diffs" && "bg-[var(--bg-surface-hover)] text-[var(--fg-default)]"' },
              { type: "add", old_num: null, new_num: 17, content: "        )}" },
              { type: "add", old_num: null, new_num: 18, content: "      >" },
              { type: "add", old_num: null, new_num: 19, content: "        Diffs" },
              { type: "add", old_num: null, new_num: 20, content: "      </button>" },
              { type: "add", old_num: null, new_num: 21, content: "    </div>" },
              { type: "add", old_num: null, new_num: 22, content: "  );" },
              { type: "add", old_num: null, new_num: 23, content: "}" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/components/organisms/StackSidebar/StackSidebar.tsx",
        change_type: "modified",
        additions: 38,
        deletions: 15,
        hunks: [
          {
            header: "@@ -1,18 +1,41 @@",
            lines: [
              { type: "context", old_num: 1, new_num: 1, content: 'import { StackConnector } from "@/components/molecules/StackConnector";' },
              { type: "context", old_num: 2, new_num: 2, content: 'import type { StackConnectorItem } from "@/components/molecules/StackConnector";' },
              { type: "add", old_num: null, new_num: 3, content: 'import { DiffFileList } from "@/components/molecules/DiffFileList";' },
              { type: "add", old_num: null, new_num: 4, content: 'import { FileTree } from "@/components/organisms/FileTree";' },
              { type: "add", old_num: null, new_num: 5, content: 'import { SidebarModeToggle } from "@/components/atoms/SidebarModeToggle";' },
              { type: "add", old_num: null, new_num: 6, content: 'import type { SidebarMode } from "@/types/sidebar";' },
              { type: "context", old_num: 3, new_num: 7, content: "" },
              { type: "del", old_num: 4, new_num: null, content: "interface StackSidebarProps {" },
              { type: "del", old_num: 5, new_num: null, content: "  stackName: string;" },
              { type: "del", old_num: 6, new_num: null, content: "  trunk: string;" },
              { type: "del", old_num: 7, new_num: null, content: "  items: StackConnectorItem[];" },
              { type: "del", old_num: 8, new_num: null, content: "  activeIndex: number;" },
              { type: "del", old_num: 9, new_num: null, content: "  onSelect: (index: number) => void;" },
              { type: "del", old_num: 10, new_num: null, content: "}" },
              { type: "add", old_num: null, new_num: 8, content: "interface StackSidebarProps {" },
              { type: "add", old_num: null, new_num: 9, content: "  stackName: string;" },
              { type: "add", old_num: null, new_num: 10, content: "  trunk: string;" },
              { type: "add", old_num: null, new_num: 11, content: "  items: StackConnectorItem[];" },
              { type: "add", old_num: null, new_num: 12, content: "  activeIndex: number;" },
              { type: "add", old_num: null, new_num: 13, content: "  onSelect: (index: number) => void;" },
              { type: "add", old_num: null, new_num: 14, content: "  sidebarMode: SidebarMode;" },
              { type: "add", old_num: null, new_num: 15, content: "  onSidebarModeChange: (mode: SidebarMode) => void;" },
              { type: "add", old_num: null, new_num: 16, content: "}" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/components/molecules/DiffFileList/DiffFileList.tsx",
        change_type: "modified",
        additions: 28,
        deletions: 16,
        hunks: [
          {
            header: "@@ -1,20 +1,32 @@",
            lines: [
              { type: "context", old_num: 1, new_num: 1, content: 'import { FileIcon } from "@/components/atoms/FileIcon";' },
              { type: "context", old_num: 2, new_num: 2, content: 'import { DiffBadge } from "@/components/atoms/DiffBadge";' },
              { type: "context", old_num: 3, new_num: 3, content: 'import { DiffStat } from "@/components/atoms/DiffStat";' },
              { type: "add", old_num: null, new_num: 4, content: 'import { cn } from "@/lib/utils";' },
              { type: "context", old_num: 4, new_num: 5, content: "" },
              { type: "del", old_num: 5, new_num: null, content: "interface DiffFileListItem {" },
              { type: "del", old_num: 6, new_num: null, content: "  path: string;" },
              { type: "del", old_num: 7, new_num: null, content: "  fileName: string;" },
              { type: "del", old_num: 8, new_num: null, content: '  changeType: "added" | "modified" | "deleted" | "renamed";' },
              { type: "del", old_num: 9, new_num: null, content: "  additions: number;" },
              { type: "del", old_num: 10, new_num: null, content: "  deletions: number;" },
              { type: "del", old_num: 11, new_num: null, content: "}" },
              { type: "add", old_num: null, new_num: 6, content: "export interface DiffFileListItem {" },
              { type: "add", old_num: null, new_num: 7, content: "  path: string;" },
              { type: "add", old_num: null, new_num: 8, content: "  fileName: string;" },
              { type: "add", old_num: null, new_num: 9, content: '  changeType: "added" | "modified" | "deleted" | "renamed";' },
              { type: "add", old_num: null, new_num: 10, content: "  additions: number;" },
              { type: "add", old_num: null, new_num: 11, content: "  deletions: number;" },
              { type: "add", old_num: null, new_num: 12, content: "}" },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/types/sidebar.ts",
        change_type: "added",
        additions: 1,
        deletions: 0,
        hunks: [
          {
            header: "@@ -0,0 +1 @@",
            lines: [
              { type: "add", old_num: null, new_num: 1, content: 'export type SidebarMode = "diffs" | "files";' },
            ],
          },
        ],
      },
      {
        path: "app/frontend/src/components/molecules/FileTreeItem/FileTreeItem.tsx",
        change_type: "modified",
        additions: 13,
        deletions: 14,
        hunks: [
          {
            header: "@@ -1,18 +1,17 @@",
            lines: [
              { type: "context", old_num: 1, new_num: 1, content: 'import { cn } from "@/lib/utils";' },
              { type: "context", old_num: 2, new_num: 2, content: 'import { FileIcon } from "@/components/atoms/FileIcon";' },
              { type: "context", old_num: 3, new_num: 3, content: 'import { IndentGuide } from "@/components/atoms/IndentGuide";' },
              { type: "del", old_num: 4, new_num: null, content: 'import { Icon } from "@/components/atoms/Icon";' },
              { type: "add", old_num: null, new_num: 4, content: 'import { Icon } from "@/components/atoms";' },
              { type: "add", old_num: null, new_num: 5, content: 'import { DiffBadge } from "@/components/atoms/DiffBadge";' },
              { type: "context", old_num: 5, new_num: 6, content: "" },
              { type: "context", old_num: 6, new_num: 7, content: "interface FileTreeItemProps {" },
            ],
          },
        ],
      },
    ],
  },

  // Branch b-006: 6-dirty-state-consolidation — no changes yet (local branch)
  "b-006": {
    total_additions: 0,
    total_deletions: 0,
    files: [],
  },
};
