import type { StackDetail } from "@/types/stack";

const now = "2026-03-21T12:00:00Z";

export const mockStackDetail: StackDetail = {
  stack: {
    id: "s-001",
    reference_number: "STK-001",
    project_id: "p-001",
    name: "frontend-mvp",
    base_branch_id: null,
    trunk: "main",
    state: "active",
    created_at: now,
    updated_at: now,
  },
  branches: [
    {
      branch: {
        id: "b-001",
        reference_number: "BR-001",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dug/frontend-mvp/1-scaffold",
        position: 1,
        head_sha: "abc1234",
        state: "merged",
        created_at: now,
        updated_at: now,
      },
      pull_request: {
        id: "pr-001",
        reference_number: "PR-001",
        branch_id: "b-001",
        external_id: 35,
        external_url: "https://github.com/org/stack-bench/pull/35",
        title: "Frontend scaffold + dark design system",
        description: "Vite + React + Tailwind 4 scaffold with dark tokens.",
        review_notes: null,
        state: "merged",
        created_at: now,
        updated_at: now,
      },
    },
    {
      branch: {
        id: "b-002",
        reference_number: "BR-002",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dug/frontend-mvp/2-shared-atoms",
        position: 2,
        head_sha: "def5678",
        state: "merged",
        created_at: now,
        updated_at: now,
      },
      pull_request: {
        id: "pr-002",
        reference_number: "PR-002",
        branch_id: "b-002",
        external_id: 36,
        external_url: "https://github.com/org/stack-bench/pull/36",
        title: "Shared atoms: Badge, Icon, Button, Collapsible, Tab",
        description: "Foundational atom components for the design system.",
        review_notes: null,
        state: "merged",
        created_at: now,
        updated_at: now,
      },
    },
    {
      branch: {
        id: "b-003",
        reference_number: "BR-003",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dug/frontend-mvp/3-stack-nav",
        position: 3,
        head_sha: "789abcd",
        state: "reviewing",
        created_at: now,
        updated_at: now,
      },
      pull_request: {
        id: "pr-003",
        reference_number: "PR-003",
        branch_id: "b-003",
        external_id: 37,
        external_url: "https://github.com/org/stack-bench/pull/37",
        title: "Stack navigation sidebar + branch list",
        description: "Left panel with stack branches, status badges, diff stats.",
        review_notes: "Check connector line alignment on short stacks.",
        state: "open",
        created_at: now,
        updated_at: now,
      },
    },
    {
      branch: {
        id: "b-004",
        reference_number: "BR-004",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dug/frontend-mvp/4-app-shell",
        position: 4,
        head_sha: null,
        state: "created",
        created_at: now,
        updated_at: now,
      },
      pull_request: null,
    },
  ],
};
