import type { StackDetail } from "@/types/stack";

const now = "2026-03-22T14:00:00Z";

export const mockStackDetail: StackDetail = {
  stack: {
    id: "s-001",
    reference_number: "STK-007",
    project_id: "p-001",
    name: "round-2-polish",
    base_branch_id: null,
    trunk: "main",
    state: "active",
    created_at: now,
    updated_at: now,
  },
  branches: [
    {
      branch: {
        id: "b-001",
        reference_number: "BR-001",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dugshub/round-2-polish/1-initial",
        position: 1,
        head_sha: "99cf8ca",
        state: "merged",
        created_at: now,
        updated_at: now,
      },
      pull_request: {
        id: "pr-001",
        reference_number: "PR-064",
        branch_id: "b-001",
        external_id: 64,
        external_url: "https://github.com/dugshub/stack-bench/pull/64",
        title: "Bootstrap Vite + React + Tailwind 4 scaffold with dark design system",
        description: "Vite + React + Tailwind 4 scaffold with dark tokens, CSS custom properties, and font setup.",
        review_notes: null,
        state: "merged",
        created_at: now,
        updated_at: now,
      },
    },
    {
      branch: {
        id: "b-002",
        reference_number: "BR-002",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dugshub/round-2-polish/2-design-polish",
        position: 2,
        head_sha: "3de4d92",
        state: "merged",
        created_at: now,
        updated_at: now,
      },
      pull_request: {
        id: "pr-002",
        reference_number: "PR-065",
        branch_id: "b-002",
        external_id: 65,
        external_url: "https://github.com/dugshub/stack-bench/pull/65",
        title: "Design polish: viewed toggle, action bar, sidebar, fonts, emerald palette",
        description: "Viewed toggle with emerald accent, action bar with collapse/expand, sidebar spacing, mono font for code paths.",
        review_notes: null,
        state: "merged",
        created_at: now,
        updated_at: now,
      },
    },
    {
      branch: {
        id: "b-003",
        reference_number: "BR-003",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dugshub/round-2-polish/3-line-interactions",
        position: 3,
        head_sha: "0079277",
        state: "reviewing",
        created_at: now,
        updated_at: now,
      },
      pull_request: {
        id: "pr-003",
        reference_number: "PR-066",
        branch_id: "b-003",
        external_id: 66,
        external_url: "https://github.com/dugshub/stack-bench/pull/66",
        title: "Add line selection and hover actions to diff viewer",
        description: "Click to select lines, shift-click for ranges, hover gutter shows + button for inline comments.",
        review_notes: "Verify hover actions don't flicker on fast mouse movement.",
        state: "open",
        created_at: now,
        updated_at: now,
      },
    },
    {
      branch: {
        id: "b-004",
        reference_number: "BR-004",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dugshub/round-2-polish/4-agent-panel",
        position: 4,
        head_sha: "e62f501",
        state: "reviewing",
        created_at: now,
        updated_at: now,
      },
      pull_request: {
        id: "pr-004",
        reference_number: "PR-067",
        branch_id: "b-004",
        external_id: 67,
        external_url: "https://github.com/dugshub/stack-bench/pull/67",
        title: "Add collapsible agent panel with mock chat",
        description: "Right-side agent panel that slides in/out, with mock chat messages and input area.",
        review_notes: null,
        state: "open",
        created_at: now,
        updated_at: now,
      },
    },
    {
      branch: {
        id: "b-005",
        reference_number: "BR-005",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dugshub/round-2-polish/5-sidebar-merge",
        position: 5,
        head_sha: "2431f31",
        state: "reviewing",
        created_at: now,
        updated_at: now,
      },
      pull_request: {
        id: "pr-005",
        reference_number: "PR-068",
        branch_id: "b-005",
        external_id: 68,
        external_url: "https://github.com/dugshub/stack-bench/pull/68",
        title: "Merge file explorer into stack sidebar with diffs/files toggle",
        description: "Unified sidebar with diffs and files tabs, file tree with dirty state indicators, and sidebar mode toggle.",
        review_notes: "Check that dirty state badges show correct colors for each change type.",
        state: "open",
        created_at: now,
        updated_at: now,
      },
    },
    {
      branch: {
        id: "b-006",
        reference_number: "BR-006",
        stack_id: "s-001",
        workspace_id: "w-001",
        name: "dugshub/round-2-polish/6-dirty-state-consolidation",
        position: 6,
        head_sha: null,
        state: "created",
        created_at: now,
        updated_at: now,
      },
      pull_request: null,
    },
  ],
};
